# Generated by Django 4.1.4 on 2022-12-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',), 'verbose_name': 'Tuman', 'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',), 'verbose_name': 'Viloyat yoki shahar', 'verbose_name_plural': 'Viloyat va shaharlar'},
        ),
        migrations.AlterModelOptions(
            name='social_network_types',
            options={'verbose_name': 'Ijtimoiy tarmoq turi', 'verbose_name_plural': 'Ijtimoiy tarmoq turlari'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='social_networs',
            field=models.ManyToManyField(blank=True, to='main.social_networks', verbose_name='Ijtimoiy tarmoqlari'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.region', verbose_name='Viloyat'),
        ),
    ]
