# Generated by Django 4.1.4 on 2023-01-01 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_district_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_networks',
            name='social_network_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='social_networs',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.district', verbose_name='Tumani'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.region', verbose_name='Viloyat yoki shahari'),
        ),
        migrations.DeleteModel(
            name='Social_network_types',
        ),
        migrations.DeleteModel(
            name='Social_networks',
        ),
    ]
