# Generated by Django 4.1.4 on 2022-12-26 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Haydovchilik guvohnoma',
                'verbose_name_plural': 'Haydovchilik guvohnomalar',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='Joy nomi')),
                ('speciality', models.CharField(max_length=150, verbose_name='Mutaxassisligi')),
                ('start_month', models.CharField(choices=[('1', 'Yanvar'), ('2', 'Fevral'), ('3', 'Mart'), ('4', 'Aprel'), ('5', 'May'), ('6', 'Iyun'), ('7', 'Iyul'), ('8', 'Avgust'), ('9', 'Sentabr'), ('10', 'Oktabr'), ('11', 'Noyabr'), ('12', 'Dekabr')], max_length=15, verbose_name='Boshlanish oyi')),
                ('start_year', models.PositiveIntegerField(verbose_name='Boshanish yili')),
                ('is_active', models.BooleanField()),
                ('end_month', models.CharField(choices=[('1', 'Yanvar'), ('2', 'Fevral'), ('3', 'Mart'), ('4', 'Aprel'), ('5', 'May'), ('6', 'Iyun'), ('7', 'Iyul'), ('8', 'Avgust'), ('9', 'Sentabr'), ('10', 'Oktabr'), ('11', 'Noyabr'), ('12', 'Dekabr')], max_length=15, verbose_name='Tugash oyi')),
                ('end_year', models.PositiveIntegerField(verbose_name='Tugash yili')),
                ('description', models.TextField(max_length=500, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Ta`lim joyi',
                'verbose_name_plural': 'Ta`lim joylar',
            },
        ),
        migrations.CreateModel(
            name='Education_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Ta`lim darajasi',
                'verbose_name_plural': 'Ta`lim darajalar',
            },
        ),
        migrations.CreateModel(
            name='Language_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Chet tili',
                'verbose_name_plural': 'Chet tillari',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leval', models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('c2', 'C2'), ('-1', 'Ona tili')], max_length=10, verbose_name='Darajasi')),
                ('language_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.language_types', verbose_name='Chet tili turi')),
            ],
            options={
                'verbose_name': 'Chet tili',
                'verbose_name_plural': 'Chet tillari',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Ko`nikma',
                'verbose_name_plural': 'Ko`nikmalar',
            },
        ),
        migrations.CreateModel(
            name='Work_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Mansabi')),
                ('company_name', models.CharField(max_length=100, verbose_name='Kompaniya nomi')),
                ('start_month', models.CharField(choices=[('1', 'Yanvar'), ('2', 'Fevral'), ('3', 'Mart'), ('4', 'Aprel'), ('5', 'May'), ('6', 'Iyun'), ('7', 'Iyul'), ('8', 'Avgust'), ('9', 'Sentabr'), ('10', 'Oktabr'), ('11', 'Noyabr'), ('12', 'Dekabr')], max_length=15, verbose_name='Boshlanish oyi')),
                ('start_year', models.PositiveIntegerField(verbose_name='Boshanish yili')),
                ('is_active', models.BooleanField()),
                ('end_month', models.CharField(choices=[('1', 'Yanvar'), ('2', 'Fevral'), ('3', 'Mart'), ('4', 'Aprel'), ('5', 'May'), ('6', 'Iyun'), ('7', 'Iyul'), ('8', 'Avgust'), ('9', 'Sentabr'), ('10', 'Oktabr'), ('11', 'Noyabr'), ('12', 'Dekabr')], max_length=15, verbose_name='Tugash oyi')),
                ('end_year', models.PositiveIntegerField(verbose_name='Tugash yili')),
                ('description', models.TextField(max_length=500, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Ishlagan joyi',
                'verbose_name_plural': 'Ishlagan joylari',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='FISH')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('birthday', models.DateField()),
                ('salary', models.PositiveIntegerField(verbose_name='Maosh')),
                ('is_freelancer', models.BooleanField(verbose_name='Frilans')),
                ('currency_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency_types')),
                ('driver_license', models.ManyToManyField(to='worker.driver_licenses')),
                ('education', models.ManyToManyField(to='worker.education')),
                ('industurial_sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.indisturial_sector', verbose_name='Sanoat soha')),
                ('languages', models.ManyToManyField(to='worker.languages')),
                ('skills', models.ManyToManyField(to='worker.skills')),
                ('specility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.speciality', verbose_name='Kasbi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('work_experience', models.ManyToManyField(to='worker.work_experience')),
            ],
            options={
                'verbose_name': 'Nomzod',
                'verbose_name_plural': 'Nomzodlar',
            },
        ),
        migrations.AddField(
            model_name='education',
            name='education_leval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.education_level'),
        ),
    ]
