# Generated by Django 4.1.4 on 2022-12-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language_types',
            options={'verbose_name': 'Chet tili turi', 'verbose_name_plural': 'Chet tili turlari'},
        ),
        migrations.RenameField(
            model_name='languages',
            old_name='leval',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_month',
            field=models.CharField(blank=True, choices=[('1', 'Yanvar'), ('2', 'Fevral'), ('3', 'Mart'), ('4', 'Aprel'), ('5', 'May'), ('6', 'Iyun'), ('7', 'Iyul'), ('8', 'Avgust'), ('9', 'Sentabr'), ('10', 'Oktabr'), ('11', 'Noyabr'), ('12', 'Dekabr')], max_length=15, null=True, verbose_name='Tugash oyi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tugash yili'),
        ),
        migrations.AlterField(
            model_name='education',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Davom etmoqda'),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='end_month',
            field=models.CharField(blank=True, choices=[('1', 'Yanvar'), ('2', 'Fevral'), ('3', 'Mart'), ('4', 'Aprel'), ('5', 'May'), ('6', 'Iyun'), ('7', 'Iyul'), ('8', 'Avgust'), ('9', 'Sentabr'), ('10', 'Oktabr'), ('11', 'Noyabr'), ('12', 'Dekabr')], max_length=15, null=True, verbose_name='Tugash oyi'),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tugash yili'),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Davom etmoqda'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='driver_license',
            field=models.ManyToManyField(blank=True, to='worker.driver_licenses'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='education',
            field=models.ManyToManyField(blank=True, to='worker.education'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_freelancer',
            field=models.BooleanField(default=False, verbose_name='Frilans'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='languages',
            field=models.ManyToManyField(blank=True, to='worker.languages'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_experience',
            field=models.ManyToManyField(blank=True, to='worker.work_experience'),
        ),
    ]
