# Generated by Django 4.1.4 on 2022-12-26 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Shart',
                'verbose_name_plural': 'Shartlar',
            },
        ),
        migrations.CreateModel(
            name='Experience_for_vacany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Ish tajribasi',
                'verbose_name_plural': 'Ish tajribasi',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Talab',
                'verbose_name_plural': 'Talablar',
            },
        ),
        migrations.CreateModel(
            name='Size_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kompaniya hajmi',
                'verbose_name_plural': 'Kompaniya hajmi',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Teglar',
                'verbose_name_plural': 'Teglar',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
            },
        ),
        migrations.CreateModel(
            name='Type_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kompaniya turi',
                'verbose_name_plural': 'Kompaniya turi',
            },
        ),
        migrations.CreateModel(
            name='Work_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Ish turi',
                'verbose_name_plural': 'Ish turlari',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Vakansiya nomi')),
                ('salary_type', models.CharField(choices=[('1', 'Naqd'), ('0', 'Suhbat orqali')], max_length=20, verbose_name='Maosh turi')),
                ('start_salary', models.PositiveIntegerField(verbose_name='Boshlang`ich maosh')),
                ('end_salary', models.PositiveIntegerField(verbose_name='Oxirgi maosh')),
                ('is_online', models.BooleanField(verbose_name='Online')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='O`zgartirildi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratildi')),
                ('conditions', models.ManyToManyField(to='company.conditions', verbose_name='Shartlar')),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency_types', verbose_name='Pul birligi')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.district', verbose_name='Tuman')),
                ('industrial_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.indisturial_sector', verbose_name='Sanoat sohasi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.region', verbose_name='Viloyat')),
                ('requirements', models.ManyToManyField(to='company.requirements', verbose_name='Talablar')),
                ('tags', models.ManyToManyField(to='company.tags', verbose_name='Teglar')),
                ('tasks', models.ManyToManyField(to='company.tasks', verbose_name='Vazifalar')),
                ('type_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.work_types', verbose_name='Ish turi')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.experience_for_vacany', verbose_name='Tajriba')),
            ],
            options={
                'verbose_name': 'Bo`sh ish o`rni',
                'verbose_name_plural': 'Bo`sh ish o`rinlari',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100, verbose_name='Kompaniya nomi')),
                ('legal_name_company', models.CharField(max_length=100, verbose_name='Kompaniyaninhg yuridik nomi')),
                ('description', models.TextField(max_length=500, verbose_name='Tavsif')),
                ('web_page', models.CharField(max_length=100, verbose_name='Web sahifa')),
                ('industrial_sector', models.ManyToManyField(to='main.indisturial_sector')),
                ('size_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.size_company', verbose_name='Hodimlar soni')),
                ('speciality', models.ManyToManyField(to='main.speciality')),
                ('type_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.type_company', verbose_name='Kompaniya turi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.vacancy', verbose_name='Bo`sh ish o`rni')),
            ],
            options={
                'verbose_name': 'Kompaniya',
                'verbose_name_plural': 'Kompaniyalar',
            },
        ),
    ]
