# Generated by Django 4.1.4 on 2023-01-03 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_social_networks_social_network_id_and_more'),
        ('company', '0002_alter_company_industrial_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Kompaniya'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.region', verbose_name='Viloyat'),
        ),
    ]
