# Generated by Django 4.1.4 on 2023-01-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_vacancy_vacancy_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Kompaniya'),
            preserve_default=False,
        ),
    ]
